In [1]:
import pandas as pd
import numpy as np
from datasets import Dataset
import os

In [2]:
base_extracted_path = '../data/extracted_corpus/Datos-MeIA-Reto-01/'

# Rutas completas a los archivos XLSX
test_file_path = os.path.join(base_extracted_path, 'MeIA_2025_test_wo_labels.xlsx')
train_file_path = os.path.join(base_extracted_path, 'MeIA_2025_train.xlsx')
print(f"Intentando cargar el archivo de prueba desde: {test_file_path}")

try:
    # Cargar el dataset de entrenamiento
    # Cargar el dataset de prueba (sin etiquetas)
    df_train= pd.read_excel(train_file_path)
    df_test = pd.read_excel(test_file_path)
    print(f"Datos de test cargados correctamente")
except FileNotFoundError:
    print(f"Error: Uno de los archivos XLSX no se encontró.")
    print(f"Asegúrate de que las rutas sean correctas: '{test_file_path}'")
    print(f"Y que la carpeta 'Datos-MelA-Reto-01' esté dentro de 'extracted_corpus'.")
except Exception as e:
    print(f"Ocurrió un error al cargar los archivos Excel: {e}")

Intentando cargar el archivo de prueba desde: ../data/extracted_corpus/Datos-MeIA-Reto-01/MeIA_2025_test_wo_labels.xlsx
Datos de test cargados correctamente

In [4]:
from ensambles_modelos import ensemble_kfold_models,ensemble_single_models,predict_single_model,prepare_test_dataframe

In [6]:
df_test = prepare_test_dataframe(df_test)
sub_1=predict_single_model(df_test, model_path='../modelos_final/model_PlanTL-GOB-ES_roberta-base-bne')

Preparando DataFrame de prueba...
Columna 'structured_text' creada.

==================================================
--- Iniciando Predicción con un Único Modelo ---
Modelo a usar: ../modelos_final/model_PlanTL-GOB-ES_roberta-base-bne
==================================================
🧠 Cargando y prediciendo con: ../modelos_final/model_PlanTL-GOB-ES_roberta-base-bne

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.

🎉 ¡Predicción completada! Archivo guardado como 'submission_single.csv'

In [6]:
df_test = prepare_test_dataframe(df_test)

Preparando DataFrame de prueba...
Columna 'structured_text' creada.

In [7]:
model_list = [
    'model_bertin-project_bertin-roberta-base-spanish',
    'model_dccuchile_bert-base-spanish-wwm-cased',
    'model_EuroBERT_EuroBERT-210m',
    'model_FacebookAI_xlm-roberta-base',
    'model_microsoft_Multilingual-MiniLM-L12-H384',
    'model_PlanTL-GOB-ES_roberta-base-bne',
    'model_tabularisai_multilingual-sentiment-analysis'
]
sub_1=ensemble_single_models(df_test, base_model_dir='../modelos_final/', model_folders=model_list)

==================================================
--- Iniciando Ensamble Simple (Sin Folds) ---
Modelos a ensamblar: ['model_bertin-project_bertin-roberta-base-spanish', 'model_dccuchile_bert-base-spanish-wwm-cased', 'model_EuroBERT_EuroBERT-210m', 'model_FacebookAI_xlm-roberta-base', 'model_microsoft_Multilingual-MiniLM-L12-H384', 'model_PlanTL-GOB-ES_roberta-base-bne', 'model_tabularisai_multilingual-sentiment-analysis']
==================================================
🧠 Cargando y prediciendo con: ../modelos_final/model_bertin-project_bertin-roberta-base-spanish

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/model_dccuchile_bert-base-spanish-wwm-cased

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/model_EuroBERT_EuroBERT-210m

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/model_FacebookAI_xlm-roberta-base

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/model_microsoft_Multilingual-MiniLM-L12-H384

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/model_PlanTL-GOB-ES_roberta-base-bne

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/model_tabularisai_multilingual-sentiment-analysis

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.

✨ Ensamblando los resultados de 7 modelos...

🎉 ¡Ensamble completado! Archivo guardado como 'submission_simple_ensemble.csv'

In [8]:
sub_1

        ID  label
0        0      3
1        1      3
2        2      2
3        3      5
4        4      4
...    ...    ...
2495  2495      4
2496  2496      3
2497  2497      3
2498  2498      3
2499  2499      2

[2500 rows x 2 columns]

In [9]:
sub_1['MeIA']='MeIA'

In [10]:
submission_df=sub_1[['MeIA','ID','label']]

In [11]:
submission_df=submission_df.rename(columns={'label':'Polarity'})

In [12]:
submission_df

      MeIA    ID  Polarity
0     MeIA     0         3
1     MeIA     1         3
2     MeIA     2         2
3     MeIA     3         5
4     MeIA     4         4
...    ...   ...       ...
2495  MeIA  2495         4
2496  MeIA  2496         3
2497  MeIA  2497         3
2498  MeIA  2498         3
2499  MeIA  2499         2

[2500 rows x 3 columns]

In [13]:
submission_filename='EMB_v4.txt'
submission_df.to_csv(submission_filename, index=False, sep=' ',header=False)

In [14]:
submission_df

      MeIA    ID  Polarity
0     MeIA     0         3
1     MeIA     1         3
2     MeIA     2         2
3     MeIA     3         5
4     MeIA     4         4
...    ...   ...       ...
2495  MeIA  2495         4
2496  MeIA  2496         3
2497  MeIA  2497         3
2498  MeIA  2498         3
2499  MeIA  2499         2

[2500 rows x 3 columns]

In [16]:
kfold_model_list = [
    'EuroBERT_EuroBERT-210m',
    'tabularisai_multilingual-sentiment-analysis',
    'PlanTL-GOB-ES_roberta-base-bne',
    'FacebookAI_xlm-roberta-base.zip',
    'dccuchile_bert-base-spanish-wwm-cased',
    'bertin-project_bertin-roberta-base-spanish'
]
sub_1=ensemble_kfold_models(df_test, base_model_dir='../modelos_final/', model_base_folders=kfold_model_list)

============================================================
--- Iniciando Ensamble K-Fold ---
Modelos base a ensamblar: ['EuroBERT_EuroBERT-210m', 'tabularisai_multilingual-sentiment-analysis', 'PlanTL-GOB-ES_roberta-base-bne', 'FacebookAI_xlm-roberta-base.zip', 'dccuchile_bert-base-spanish-wwm-cased', 'bertin-project_bertin-roberta-base-spanish']
============================================================

Procesando modelo base: EuroBERT_EuroBERT-210m
🧠 Cargando y prediciendo con: ../modelos_final/EuroBERT_EuroBERT-210m/fold_1

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/EuroBERT_EuroBERT-210m/fold_2

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/EuroBERT_EuroBERT-210m/fold_3

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/EuroBERT_EuroBERT-210m/fold_4

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/EuroBERT_EuroBERT-210m/fold_5

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
  -> Ensamblando los 5 folds para EuroBERT_EuroBERT-210m...
  -> ✅ Predicción robusta para EuroBERT_EuroBERT-210m generada.

Procesando modelo base: tabularisai_multilingual-sentiment-analysis
🧠 Cargando y prediciendo con: ../modelos_final/tabularisai_multilingual-sentiment-analysis/fold_1

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/tabularisai_multilingual-sentiment-analysis/fold_2

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/tabularisai_multilingual-sentiment-analysis/fold_3

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/tabularisai_multilingual-sentiment-analysis/fold_4

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/tabularisai_multilingual-sentiment-analysis/fold_5

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
  -> Ensamblando los 5 folds para tabularisai_multilingual-sentiment-analysis...
  -> ✅ Predicción robusta para tabularisai_multilingual-sentiment-analysis generada.

Procesando modelo base: PlanTL-GOB-ES_roberta-base-bne
🧠 Cargando y prediciendo con: ../modelos_final/PlanTL-GOB-ES_roberta-base-bne/fold_1

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/PlanTL-GOB-ES_roberta-base-bne/fold_2

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/PlanTL-GOB-ES_roberta-base-bne/fold_3

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/PlanTL-GOB-ES_roberta-base-bne/fold_4

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/PlanTL-GOB-ES_roberta-base-bne/fold_5

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
  -> Ensamblando los 5 folds para PlanTL-GOB-ES_roberta-base-bne...
  -> ✅ Predicción robusta para PlanTL-GOB-ES_roberta-base-bne generada.

Procesando modelo base: FacebookAI_xlm-roberta-base.zip
🧠 Cargando y prediciendo con: ../modelos_final/FacebookAI_xlm-roberta-base.zip/fold_1

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/FacebookAI_xlm-roberta-base.zip/fold_2

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/FacebookAI_xlm-roberta-base.zip/fold_3

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/FacebookAI_xlm-roberta-base.zip/fold_4

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/FacebookAI_xlm-roberta-base.zip/fold_5

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
  -> Ensamblando los 5 folds para FacebookAI_xlm-roberta-base.zip...
  -> ✅ Predicción robusta para FacebookAI_xlm-roberta-base.zip generada.

Procesando modelo base: dccuchile_bert-base-spanish-wwm-cased
🧠 Cargando y prediciendo con: ../modelos_final/dccuchile_bert-base-spanish-wwm-cased/fold_1

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/dccuchile_bert-base-spanish-wwm-cased/fold_2

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/dccuchile_bert-base-spanish-wwm-cased/fold_3

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/dccuchile_bert-base-spanish-wwm-cased/fold_4

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/dccuchile_bert-base-spanish-wwm-cased/fold_5

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
  -> Ensamblando los 5 folds para dccuchile_bert-base-spanish-wwm-cased...
  -> ✅ Predicción robusta para dccuchile_bert-base-spanish-wwm-cased generada.

Procesando modelo base: bertin-project_bertin-roberta-base-spanish
🧠 Cargando y prediciendo con: ../modelos_final/bertin-project_bertin-roberta-base-spanish/fold_1

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/bertin-project_bertin-roberta-base-spanish/fold_2

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/bertin-project_bertin-roberta-base-spanish/fold_3

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/bertin-project_bertin-roberta-base-spanish/fold_4

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
🧠 Cargando y prediciendo con: ../modelos_final/bertin-project_bertin-roberta-base-spanish/fold_5

Map:   0%|          | 0/2500 [00:00<?, ? examples/s]

  -> ✅ Predicciones obtenidas.
  -> Ensamblando los 5 folds para bertin-project_bertin-roberta-base-spanish...
  -> ✅ Predicción robusta para bertin-project_bertin-roberta-base-spanish generada.

✨ Ensamblando las 6 predicciones robustas de cada tipo de modelo...

🎉 ¡Ensamble K-Fold completado! Archivo guardado como 'submission_kfold_ensemble.csv'

In [17]:
sub_1

        ID  label
0        0      3
1        1      3
2        2      2
3        3      5
4        4      5
...    ...    ...
2495  2495      4
2496  2496      3
2497  2497      3
2498  2498      3
2499  2499      2

[2500 rows x 2 columns]

In [18]:
sub_1['MeIA']='MeIA'
submission_df=sub_1[['MeIA','ID','label']]
submission_df=submission_df.rename(columns={'label':'Polarity'})
submission_df

      MeIA    ID  Polarity
0     MeIA     0         3
1     MeIA     1         3
2     MeIA     2         2
3     MeIA     3         5
4     MeIA     4         5
...    ...   ...       ...
2495  MeIA  2495         4
2496  MeIA  2496         3
2497  MeIA  2497         3
2498  MeIA  2498         3
2499  MeIA  2499         2

[2500 rows x 3 columns]

In [19]:
submission_filename='EMB_v5.txt'
submission_df.to_csv(submission_filename, index=False, sep=' ',header=False)