In [1]:
from models import run_kfold_training_workflow

2025-06-18 20:10:11.476174: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1750288211.894598   33279 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1750288212.007790   33279 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1750288213.043342   33279 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1750288213.043365   33279 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1750288213.043367   33279 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1750288213.043369   33279 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-06-18 20:10:13.171153: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
import zipfile
import os
import pandas as pd
import numpy as np
zip_file_path = '../data/MeIA2025-Reto-01.zip'

extracted_folder_path = '../data/extracted_corpus/'

# 2. Crear la carpeta de extracción si no existe
if not os.path.exists(extracted_folder_path):
    os.makedirs(extracted_folder_path)
    print(f"Carpeta '{extracted_folder_path}' creada.")
# 3. Descomprimir archivo  
try:
    with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
        zip_ref.extractall(extracted_folder_path)
    print(f"'{zip_file_path}' descomprimido exitosamente en '{extracted_folder_path}'.")
except FileNotFoundError:
    print(f"Error: El archivo ZIP no se encontró en '{zip_file_path}'. Verifica la ruta.")
except Exception as e:
    print(f"Ocurrió un error al descomprimir el archivo: {e}")
    
# 4. Listar los archivos descomprimidos (para verificar)
print("\nArchivos en la carpeta del corpus:")
corpus_files = os.listdir(extracted_folder_path)
for file_name in corpus_files:
    print(f"- {file_name}")

# Definir la ruta base donde se extrajo el contenido del ZIP
# Asegúrate de que esta ruta sea correcta relativa a tu notebook test.ipynb
# Si tu notebook está en 'notebooks/' y la extracción está en 'data/extracted_corpus/Datos-MelA-Reto-01/'
base_extracted_path = '../data/extracted_corpus/Datos-MeIA-Reto-01/'

# Rutas completas a los archivos XLSX
train_file_path = os.path.join(base_extracted_path, 'MeIA_2025_train.xlsx')
test_file_path = os.path.join(base_extracted_path, 'MeIA_2025_test_wo_labels.xlsx')

print(f"Intentando cargar el archivo de entrenamiento desde: {train_file_path}")
print(f"Intentando cargar el archivo de prueba desde: {test_file_path}")

try:
    # Cargar el dataset de entrenamiento
    
    df_train = pd.read_excel(train_file_path)
    print(f"Datos de entrenamiento cargados correctamente")
    # Cargar el dataset de prueba (sin etiquetas)
    df_test = pd.read_excel(test_file_path)
    print(f"Datos de test cargados correctamente")


except FileNotFoundError:
    print(f"Error: Uno de los archivos XLSX no se encontró.")
    print(f"Asegúrate de que las rutas sean correctas: '{train_file_path}' y '{test_file_path}'")
    print(f"Y que la carpeta 'Datos-MelA-Reto-01' esté dentro de 'extracted_corpus'.")
except Exception as e:
    print(f"Ocurrió un error al cargar los archivos Excel: {e}")
    
    
df_train['structured_text'] = df_train.apply(
    lambda row: f"tipo: {str(row['Type']).lower()}. pueblo: {str(row['Town']).lower()}. reseña: {str(row['Review']).lower()}",
    axis=1
)

'../data/MeIA2025-Reto-01.zip' descomprimido exitosamente en '../data/extracted_corpus/'.

Archivos en la carpeta del corpus:
- Datos-MeIA-Reto-01
Intentando cargar el archivo de entrenamiento desde: ../data/extracted_corpus/Datos-MeIA-Reto-01/MeIA_2025_train.xlsx
Intentando cargar el archivo de prueba desde: ../data/extracted_corpus/Datos-MeIA-Reto-01/MeIA_2025_test_wo_labels.xlsx
Datos de entrenamiento cargados correctamente
Datos de test cargados correctamente

In [3]:
run_kfold_training_workflow(
    df=df_train,
    model_name='PlanTL-GOB-ES/roberta-base-bne',
    n_splits=5,
    output_base_dir='../modelos_final' # O la ruta que prefieras
)

🚀 Iniciando Proceso Completo de K-Fold (K=5) para el modelo: PlanTL-GOB-ES/roberta-base-bne

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Todos los folds para este modelo se guardarán dentro de: '../modelos_final/PlanTL-GOB-ES_roberta-base-bne'

--- 🚀 Iniciando Entrenamiento FOLD 1 ---

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at PlanTL-GOB-ES/roberta-base-bne and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/joad/Personal/Desafio/Desafio_NLP_UNAM/notebooks/models.py:62: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Guardando el mejor modelo del Fold 1 en: '../modelos_final/PlanTL-GOB-ES_roberta-base-bne/fold_1'

--- 🚀 Iniciando Entrenamiento FOLD 2 ---

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at PlanTL-GOB-ES/roberta-base-bne and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/joad/Personal/Desafio/Desafio_NLP_UNAM/notebooks/models.py:62: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Guardando el mejor modelo del Fold 2 en: '../modelos_final/PlanTL-GOB-ES_roberta-base-bne/fold_2'

--- 🚀 Iniciando Entrenamiento FOLD 3 ---

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at PlanTL-GOB-ES/roberta-base-bne and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/joad/Personal/Desafio/Desafio_NLP_UNAM/notebooks/models.py:62: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Guardando el mejor modelo del Fold 3 en: '../modelos_final/PlanTL-GOB-ES_roberta-base-bne/fold_3'

--- 🚀 Iniciando Entrenamiento FOLD 4 ---

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at PlanTL-GOB-ES/roberta-base-bne and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/joad/Personal/Desafio/Desafio_NLP_UNAM/notebooks/models.py:62: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Guardando el mejor modelo del Fold 4 en: '../modelos_final/PlanTL-GOB-ES_roberta-base-bne/fold_4'

--- 🚀 Iniciando Entrenamiento FOLD 5 ---

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at PlanTL-GOB-ES/roberta-base-bne and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/joad/Personal/Desafio/Desafio_NLP_UNAM/notebooks/models.py:62: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Guardando el mejor modelo del Fold 5 en: '../modelos_final/PlanTL-GOB-ES_roberta-base-bne/fold_5'

============================================================
--- RESUMEN FINAL DE LA VALIDACIÓN CRUZADA ---
Modelo: PlanTL-GOB-ES/roberta-base-bne
F1-Scores por Fold: [0.5921, 0.5843, 0.5588, 0.5444, 0.569]
Rendimiento Promedio (Mean F1-Macro): 0.5697 ± 0.0172
============================================================

{'mean_f1': 0.5697272013346782, 'std_f1': 0.017164119686467243}

In [4]:
run_kfold_training_workflow(
    df=df_train,
    model_name= "tabularisai/multilingual-sentiment-analysis",
    n_splits=5,
    output_base_dir='../modelos_final' # O la ruta que prefieras
)

🚀 Iniciando Proceso Completo de K-Fold (K=5) para el modelo: tabularisai/multilingual-sentiment-analysis

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Todos los folds para este modelo se guardarán dentro de: '../modelos_final/tabularisai_multilingual-sentiment-analysis'

--- 🚀 Iniciando Entrenamiento FOLD 1 ---

/home/joad/Personal/Desafio/Desafio_NLP_UNAM/notebooks/models.py:62: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Guardando el mejor modelo del Fold 1 en: '../modelos_final/tabularisai_multilingual-sentiment-analysis/fold_1'

--- 🚀 Iniciando Entrenamiento FOLD 2 ---

/home/joad/Personal/Desafio/Desafio_NLP_UNAM/notebooks/models.py:62: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Guardando el mejor modelo del Fold 2 en: '../modelos_final/tabularisai_multilingual-sentiment-analysis/fold_2'

--- 🚀 Iniciando Entrenamiento FOLD 3 ---

/home/joad/Personal/Desafio/Desafio_NLP_UNAM/notebooks/models.py:62: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Guardando el mejor modelo del Fold 3 en: '../modelos_final/tabularisai_multilingual-sentiment-analysis/fold_3'

--- 🚀 Iniciando Entrenamiento FOLD 4 ---

/home/joad/Personal/Desafio/Desafio_NLP_UNAM/notebooks/models.py:62: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Guardando el mejor modelo del Fold 4 en: '../modelos_final/tabularisai_multilingual-sentiment-analysis/fold_4'

--- 🚀 Iniciando Entrenamiento FOLD 5 ---

/home/joad/Personal/Desafio/Desafio_NLP_UNAM/notebooks/models.py:62: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Guardando el mejor modelo del Fold 5 en: '../modelos_final/tabularisai_multilingual-sentiment-analysis/fold_5'

============================================================
--- RESUMEN FINAL DE LA VALIDACIÓN CRUZADA ---
Modelo: tabularisai/multilingual-sentiment-analysis
F1-Scores por Fold: [0.562, 0.5589, 0.5307, 0.5014, 0.5216]
Rendimiento Promedio (Mean F1-Macro): 0.5349 ± 0.0229
============================================================

{'mean_f1': 0.5349065906679109, 'std_f1': 0.022908491472990372}

In [5]:
run_kfold_training_workflow(
    df=df_train,
    model_name= "bertin-project/bertin-roberta-base-spanish",
    n_splits=5,
    output_base_dir='../modelos_final' # O la ruta que prefieras
)

🚀 Iniciando Proceso Completo de K-Fold (K=5) para el modelo: bertin-project/bertin-roberta-base-spanish

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Todos los folds para este modelo se guardarán dentro de: '../modelos_final/bertin-project_bertin-roberta-base-spanish'

--- 🚀 Iniciando Entrenamiento FOLD 1 ---

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at bertin-project/bertin-roberta-base-spanish and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/joad/Personal/Desafio/Desafio_NLP_UNAM/notebooks/models.py:62: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Guardando el mejor modelo del Fold 1 en: '../modelos_final/bertin-project_bertin-roberta-base-spanish/fold_1'

--- 🚀 Iniciando Entrenamiento FOLD 2 ---

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at bertin-project/bertin-roberta-base-spanish and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/joad/Personal/Desafio/Desafio_NLP_UNAM/notebooks/models.py:62: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Guardando el mejor modelo del Fold 2 en: '../modelos_final/bertin-project_bertin-roberta-base-spanish/fold_2'

--- 🚀 Iniciando Entrenamiento FOLD 3 ---

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at bertin-project/bertin-roberta-base-spanish and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/joad/Personal/Desafio/Desafio_NLP_UNAM/notebooks/models.py:62: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Guardando el mejor modelo del Fold 3 en: '../modelos_final/bertin-project_bertin-roberta-base-spanish/fold_3'

--- 🚀 Iniciando Entrenamiento FOLD 4 ---

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at bertin-project/bertin-roberta-base-spanish and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/joad/Personal/Desafio/Desafio_NLP_UNAM/notebooks/models.py:62: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Guardando el mejor modelo del Fold 4 en: '../modelos_final/bertin-project_bertin-roberta-base-spanish/fold_4'

--- 🚀 Iniciando Entrenamiento FOLD 5 ---

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at bertin-project/bertin-roberta-base-spanish and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/joad/Personal/Desafio/Desafio_NLP_UNAM/notebooks/models.py:62: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Guardando el mejor modelo del Fold 5 en: '../modelos_final/bertin-project_bertin-roberta-base-spanish/fold_5'

============================================================
--- RESUMEN FINAL DE LA VALIDACIÓN CRUZADA ---
Modelo: bertin-project/bertin-roberta-base-spanish
F1-Scores por Fold: [0.5787, 0.5494, 0.5705, 0.5554, 0.5729]
Rendimiento Promedio (Mean F1-Macro): 0.5654 ± 0.0111
============================================================

{'mean_f1': 0.5653704976217622, 'std_f1': 0.011091901861512448}

In [3]:
run_kfold_training_workflow(
    df=df_train,
    model_name= "EuroBERT/EuroBERT-210m",
    n_splits=5,
    output_base_dir='../modelos_final' # O la ruta que prefieras
)

🚀 Iniciando Proceso Completo de K-Fold (K=5) para el modelo: EuroBERT/EuroBERT-210m

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Todos los folds para este modelo se guardarán dentro de: '../modelos_final/EuroBERT_EuroBERT-210m'

--- 🚀 Iniciando Entrenamiento FOLD 1 ---

Some weights of EuroBertForSequenceClassification were not initialized from the model checkpoint at EuroBERT/EuroBERT-210m and are newly initialized: ['classifier.bias', 'classifier.weight', 'dense.bias', 'dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/joad/Personal/Desafio/Desafio_NLP_UNAM/notebooks/models.py:62: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Guardando el mejor modelo del Fold 1 en: '../modelos_final/EuroBERT_EuroBERT-210m/fold_1'

--- 🚀 Iniciando Entrenamiento FOLD 2 ---

Some weights of EuroBertForSequenceClassification were not initialized from the model checkpoint at EuroBERT/EuroBERT-210m and are newly initialized: ['classifier.bias', 'classifier.weight', 'dense.bias', 'dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/joad/Personal/Desafio/Desafio_NLP_UNAM/notebooks/models.py:62: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Guardando el mejor modelo del Fold 2 en: '../modelos_final/EuroBERT_EuroBERT-210m/fold_2'

--- 🚀 Iniciando Entrenamiento FOLD 3 ---

Some weights of EuroBertForSequenceClassification were not initialized from the model checkpoint at EuroBERT/EuroBERT-210m and are newly initialized: ['classifier.bias', 'classifier.weight', 'dense.bias', 'dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/joad/Personal/Desafio/Desafio_NLP_UNAM/notebooks/models.py:62: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Guardando el mejor modelo del Fold 3 en: '../modelos_final/EuroBERT_EuroBERT-210m/fold_3'

--- 🚀 Iniciando Entrenamiento FOLD 4 ---

Some weights of EuroBertForSequenceClassification were not initialized from the model checkpoint at EuroBERT/EuroBERT-210m and are newly initialized: ['classifier.bias', 'classifier.weight', 'dense.bias', 'dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/joad/Personal/Desafio/Desafio_NLP_UNAM/notebooks/models.py:62: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Guardando el mejor modelo del Fold 4 en: '../modelos_final/EuroBERT_EuroBERT-210m/fold_4'

--- 🚀 Iniciando Entrenamiento FOLD 5 ---

Some weights of EuroBertForSequenceClassification were not initialized from the model checkpoint at EuroBERT/EuroBERT-210m and are newly initialized: ['classifier.bias', 'classifier.weight', 'dense.bias', 'dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/joad/Personal/Desafio/Desafio_NLP_UNAM/notebooks/models.py:62: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Guardando el mejor modelo del Fold 5 en: '../modelos_final/EuroBERT_EuroBERT-210m/fold_5'

============================================================
--- RESUMEN FINAL DE LA VALIDACIÓN CRUZADA ---
Modelo: EuroBERT/EuroBERT-210m
F1-Scores por Fold: [0.5577, 0.5038, 0.5504, 0.445, 0.5548]
Rendimiento Promedio (Mean F1-Macro): 0.5223 ± 0.0434
============================================================

{'mean_f1': 0.5223366100026705, 'std_f1': 0.04338527107326628}